### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Hjord** [wbinglee/zsh-wakatime#15]
Does this still work?
No commands seems to get tracked.

**Comment by wbinglee** [comment]
Yes, it's working, I use it every day.  

You may check below things:
- Make sure this zsh plugin configured right, make sure this repo is downloaded and configured right in oh-my-zsh or antigen
- Make sure `wakatime` cli is installed  by `pip install wakatime`, try to run command `wakatime --write --plugin "zsh-wakatime/0.0.1" --entity-type app --project Terminal --entity ls` to verify it.
- Try to run `ps -ef | grep waketime` as quick as you can. You may see some wakatime cli process running in the background. Otherwise, double check your zsh config.
-  Go your browser and access url `https://wakatime.com/api/v1/users/current/heartbeats?date=2017-07-03` (with your current date). You should see your latest command.

**Comment by Hjord** [comment]
Thank you for your help.

Nothing seems to happen when I run the command `ps -ef | grep waketime`
But the command run in step two, show up in step four, so something must be working.

**Comment by Hjord** [comment]
Not sure what I did. But it appears I got it working.
Thank you.

**Comment by wbinglee** [comment]
Glad to know it works for you now.

**Comment by expl0r3rgu1** [comment]
I didn't have the `wakatime` python package installed, only `zsh-wakatime`. Installing it solved the issue for me! Furthermore keep in mind that you can't pip install globally anymore, you either need to install the `pipx` utility or create a python venv.

Came back to this to keep my current timetracking setup into wakatime after switching from standard editors (like vscode or even neovim) to opencode
